setting:
  sandbox     : true
  request_log : false
  timezone    : PRC
  secret_key  : xxxxxxxxxxxxxxxx
  default     : 1001001|XT_app|zh_CN

db_data:
    adapter   : mysql
    host      : 127.0.0.1
    port      : 3306
    user      : root
    pass      : root
    db        : v3-rpc
    charset   : utf8

db_logs:
    adapter   : mysql
    host      : 127.0.0.1
    port      : 3306
    user      : root
    pass      : root
    db        : v3_logs
    charset   : utf8mb4

db_trade:
    adapter   : mysql
    host      : 127.0.0.1
    port      : 3306
    user      : root
    pass      : root
    db        : v3-trade
    charset   : utf8mb4


db_account:
  adapter   : mysql
  host      : 127.0.0.1
  port      : 3306
  user      : root
  pass      : root
  db        : v3-account
  charset   : utf8mb4

redis:
    host      : 127.0.0.1
    port      : 6379

# 允许的IP列表, 逗号分割
ip_allow:
    127.0.0.1